{
 "title": "test",
 "time": { "from": "1949-12-31T21:00:00.000Z", "to": "2024-12-30T21:00:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH monthly_avg AS (\r\n    SELECT\r\n        c.country,\r\n        (EXTRACT(YEAR FROM w.date)::int / 10) * 10 AS decade,\r\n        EXTRACT(MONTH FROM w.date)::int AS month,\r\n        AVG(w.tavg) AS avg_tavg\r\n    FROM weather w\r\n    JOIN cities c ON w.city_id = c.id\r\n    WHERE c.country IN ('Russia', 'Canada') AND w.tavg IS NOT NULL\r\n    GROUP BY c.country, decade, month\r\n),\r\nmax_month_per_decade AS (\r\n    SELECT DISTINCT ON (country, decade)\r\n        country,\r\n        decade,\r\n        month,\r\n        avg_tavg\r\n    FROM monthly_avg\r\n    ORDER BY country, decade, avg_tavg DESC\r\n)\r\nSELECT\r\n    TO_TIMESTAMP(decade || '-01-01', 'YYYY-MM-DD') AS \"time\",\r\n    country,\r\n    month AS peak_month\r\nFROM max_month_per_decade\r\nORDER BY \"time\";\r\n"
    }
   ]
  },
  { "title": "Анализ осадков", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Анализ осадков ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(EXTRACT(YEAR FROM w.date)::int || '-01-01', 'YYYY-MM-DD') AS \"time\",\r\n  c.country,\r\n  SUM(w.prcp) AS \"Общие осадки (мм)\",\r\n  SUM(w.snow) AS \"Общий снег (мм)\",\r\n  CASE\r\n    WHEN SUM(w.prcp) > 0 THEN SUM(w.snow) / SUM(w.prcp)\r\n    ELSE NULL\r\n  END AS \"Доля снега в осадках\"\r\nFROM weather w\r\nJOIN cities c ON w.city_id = c.id\r\nWHERE c.country IN ('Germany')\r\n  AND w.prcp IS NOT NULL AND w.snow IS NOT NULL\r\nGROUP BY c.country, EXTRACT(YEAR FROM w.date)\r\nORDER BY \"time\"\r\n"
    }
   ]
  },
  { "title": "Температура и климат", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Средний суточный температурный диапазон по годам в России",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_TIMESTAMP(year || '-01-01', 'YYYY-MM-DD') AS \"time\",\r\n    CASE\r\n        WHEN city = 'Moscow' THEN 'Москва'\r\n        WHEN city = 'Yakutsk' THEN 'Якутск'\r\n        WHEN city = 'Pskov' THEN 'Псков'\r\n        WHEN city = 'Bratsk' THEN 'Братск'\r\n    END AS metric,\r\n    AVG(avg_range) AS value\r\nFROM (\r\n    SELECT\r\n        c.name AS city,\r\n        c.country,\r\n        EXTRACT(YEAR FROM w.date) AS year,\r\n        AVG(w.tmax - w.tmin) AS avg_range\r\n    FROM\r\n        weather w\r\n    JOIN\r\n        cities c ON w.city_id = c.id\r\n    WHERE\r\n        w.tmax IS NOT NULL AND w.tmin IS NOT NULL\r\n        AND (\r\n            (c.country = 'Russia' AND c.name IN ('Moscow', 'Yakutsk', 'Pskov', 'Bratsk'))\r\n        )\r\n    GROUP BY c.name, c.country, year\r\n) AS sub\r\nGROUP BY city, country, year\r\nORDER BY \"time\"\r\n"
    }
   ]
  },
  {
   "title": "Средний суточный температурный диапазон по годам по странам",
   "type": "timeseries",
   "description": "Как меняется разница между Tmax и Tmin: 1950–2020, 3 страны",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_TIMESTAMP(year || '-01-01', 'YYYY-MM-DD') AS \"time\",\r\n    country,\r\n    AVG(avg_range) AS avg_daily_range\r\nFROM avg_city_temp_by_year\r\nWHERE country IN ('Russia', 'United States', 'Canada') AND avg_range IS NOT NULL\r\nGROUP BY year, country\r\nORDER BY \"time\"\r\n"
    }
   ]
  },
  {
   "title": "График среднегодовых температур по странам",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(year || '-01-01', 'YYYY-MM-DD') AS \"time\",\r\n  avg_temp,\r\n  country\r\nFROM avg_country_temp_by_year\r\nORDER BY \"time\"\r\n"
    }
   ]
  }
 ]
}